trigger: none

parameters:
- name: clientId
  displayName: Client name
  type: string
  
stages:
- ${{ if ne(parameters.clientId, '') }}:
  - template: "global-pipeline-inputs/${{parameters.clientId}}_environments.yml"
