parameters:
  - name: clientEnvironments
    type: object

stages:
  - ${{ each environment in parameters.clientEnvironments.Platforms }}:
      - stage: Create_${{ environment.Platform }}_Account_${{parameters.clientEnvironments.ProjectName}}_${{ environment.AccountSequenceNumber}}
        displayName: "Create ${{ environment.Platform }} account for ${{parameters.clientEnvironments.ProjectName}} - ${{ environment.AccountSequenceNumber}} "
        condition: and(containsValue(environment, 'Networking'), greater(length(environment.Networking), 3))
        jobs:
          - template: jobs-templates/job_t1.yaml # Template reference
            parameters:
              environment: ${{environment}}
              projectName: ${{parameters.clientEnvironments.ProjectName}}
          # ... more Azure-specific jobs ...
      - stage: Move_Account_to_Right_OU_or_MG_${{ environment.Platform }}_${{parameters.clientEnvironments.ProjectName}}_${{ environment.AccountSequenceNumber}}
        displayName: "Move the account to the right OU or Management group ${{parameters.clientEnvironments.ProjectName}} "
        jobs:
          - template: jobs-templates/job_t1.yaml # Template reference
            parameters:
              environment: ${{environment}} 
              projectName: ${{parameters.clientEnvironments.ProjectName}}
      - ${{ if containsValue(environment, 'Networking') }}:
        - stage: Fetch_Hub_and_Spoke_data_${{ environment.Platform }}_${{parameters.clientEnvironments.ProjectName}}_${{ environment.AccountSequenceNumber}}
          displayName: "Fetch HUB data and check for available CIDR block on ${{ environment.Platform }}  - ${{ environment.AccountSequenceNumber}}"
          jobs:
            - template: jobs-templates/job_t1.yaml
              parameters:
                environment: ${{ environment}}
                projectName: ${{parameters.clientEnvironments.ProjectName}}

        - stage: Run_Terrafrom_Config_${{ environment.Platform }}_${{parameters.clientEnvironments.ProjectName}}_${{ environment.AccountSequenceNumber}}
          displayName: "Run Terraform configuration for ${{parameters.clientEnvironments.ProjectName}} on ${{ environment.Platform }} -  ${{ environment.AccountSequenceNumber}}"
          jobs:
            - template: jobs-templates/job_t1.yaml
              parameters:
                environment: ${{ environment}}
                projectName: ${{parameters.clientEnvironments.ProjectName}}

      - stage: Access_Provisionning_${{ environment.Platform }}_${{parameters.clientEnvironments.ProjectName}}_${{ environment.AccountSequenceNumber}}
        displayName: "Access provisionning for ${{parameters.clientEnvironments.ProjectName}} on ${{ environment.Platform }} - ${{ environment.AccountSequenceNumber}}"
        jobs:
          - template: jobs-templates/job_t1.yaml # Template reference
            parameters:
              environment: ${{environment}} 
              projectName: ${{parameters.clientEnvironments.ProjectName}}
